// Regenerates src/content/sponsors.ts from the public sponsors of every MetrolistGroup member.
// Needs GITHUB_TOKEN (or a logged-in gh CLI). On any failure the committed snapshot is kept.
import { writeFile } from 'node:fs/promises'

const ORG = 'MetrolistGroup'
const out = new URL('../src/content/sponsors.ts', import.meta.url)

try {
  const token = process.env.GITHUB_TOKEN || (await Bun.$`gh auth token`.text()).trim()
  const headers = { Authorization: `Bearer ${token}`, 'User-Agent': 'metrosite' }
  const api = async (path: string, init?: RequestInit) => {
    const res = await fetch(`https://api.github.com${path}`, { ...init, headers })
    if (!res.ok) throw new Error(`${path}: ${res.status}`)
    return res.json() as Promise<any>
  }

  const members: { login: string }[] = await api(`/orgs/${ORG}/members?per_page=100`)
  const query = `query($u:String!){ user(login:$u){ sponsors(first:100){ nodes{ ... on User{login name} ... on Organization{login name} } } } }`
  const lists = await Promise.all(members.map(async ({ login }) => {
    const res = await api('/graphql', { method: 'POST', body: JSON.stringify({ query, variables: { u: login } }) })
    if (res.errors) throw new Error(res.errors[0].message)
    return res.data.user.sponsors.nodes as { login: string; name: string | null }[]
  }))

  // The sponsors field only returns public sponsors, so private ones never appear.
  const unique = new Map<string, string>()
  for (const s of lists.flat()) unique.set(s.login.toLowerCase(), s.name || s.login)
  const sponsors = lists.flat()
    .filter((s, i, all) => all.findIndex(o => o.login.toLowerCase() === s.login.toLowerCase()) === i)
    .map(s => ({ login: s.login, name: unique.get(s.login.toLowerCase())! }))
    .sort((a, b) => a.login.localeCompare(b.login, 'en', { sensitivity: 'base' }))

  const rows = sponsors.map(s => `  { login: ${JSON.stringify(s.login)}, name: ${JSON.stringify(s.name)} },`).join('\n')
  await writeFile(out, `// Generated by scripts/sponsors.ts. Do not edit by hand.
export type Sponsor = {
  login: string
  name: string
}

export const SPONSORS: Sponsor[] = [
${rows}
]
`)
  console.log(`sponsors: ${sponsors.length} public sponsors from ${members.length} members`)
} catch (error) {
  console.warn(`sponsors: fetch failed, keeping committed list (${(error as Error).message})`)
}
